/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.sviperll.repository;

/**
 *
 * @author vir
 */
public interface AutogeneratedKeyIndexedRepositoryConfiguration<K, V> extends IndexedRepositoryConfiguration<K, V> {

    StorableTypeDefinition<K> getAutogeneratedKeyDefinition();

}
