/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.sviperll.repository;

/**
 *
 * @author vir
 */
public class RepositoryConfigurations {
    public static <K, V> AutogeneratedKeyIndexedRepositoryConfiguration<K, V> autogeneratedKeyIndexed(final String tableName, final StorableTypeDefinition<K> key, final StorableTypeDefinition<K> autogeneratedKey, final StorableTypeDefinition<V> value) {
        return new AutogeneratedKeyIndexedRepositoryConfiguration<K, V>() {
            @Override
            public StorableTypeDefinition<K> getAutogeneratedKeyDefinition() {
                return autogeneratedKey;
            }

            @Override
            public StorableTypeDefinition<V> getValueDefinition() {
                return value;
            }

            @Override
            public String getTableName() {
                return tableName;
            }

            @Override
            public StorableTypeDefinition<K> getKeyDefinition() {
                return key;
            }
        };
    }

    public static <K, V> IndexedRepositoryConfiguration<K, V> indexed(final String tableName, final StorableTypeDefinition<K> key, final StorableTypeDefinition<V> value) {
        return new IndexedRepositoryConfiguration<K, V>() {
            @Override
            public StorableTypeDefinition<K> getKeyDefinition() {
                return key;
            }

            @Override
            public StorableTypeDefinition<V> getValueDefinition() {
                return value;
            }

            @Override
            public String getTableName() {
                return tableName;
            }
        };
    }

    public static <E, O> ReadableRepositoryConfiguration<E, O> readable(final String tableName, final StorableTypeDefinition<E> entry, final StorableTypeDefinition<O> ordering) {
        return new ReadableRepositoryConfiguration<E, O>() {

            @Override
            public StorableTypeDefinition<E> getEntryDefinition() {
                return entry;
            }

            @Override
            public StorableTypeDefinition<O> getOrderingDefinition() {
                return ordering;
            }

            @Override
            public String getTableName() {
                return tableName;
            }
        };
    }

    public static <K, E, O> ReadableRepositoryDirectoryConfiguration<K, E, O> readableDirectory(final String tableName, final StorableTypeDefinition<E> entry, final StorableTypeDefinition<K> key, final StorableTypeDefinition<O> ordering) {
        return new ReadableRepositoryDirectoryConfiguration<K, E, O>() {

            @Override
            public StorableTypeDefinition<E> getEntryDefinition() {
                return entry;
            }

            @Override
            public StorableTypeDefinition<O> getOrderingDefinition() {
                return ordering;
            }

            @Override
            public String getTableName() {
                return tableName;
            }

            @Override
            public StorableTypeDefinition<K> getKeyDefinition() {
                return key;
            }
        };
    }

    private RepositoryConfigurations() {
    }
}
