/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.sviperll.repository;

import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author vir
 */
public interface SQLConnection extends SQLTransactionManager {
    PreparedStatement prepareStatement(String sql) throws SQLException;
    PreparedStatement prepareStatementWithAutogeneratedKeys(String sql) throws SQLException;
    PreparedStatement prepareStatementWithoutAutogeneratedKeys(String sql) throws SQLException;
    void close() throws SQLException;
}
