/*
 * Copyright (c) 2014, Victor Nazarov <asviraspossible@gmail.com>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Victor Nazarov nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.github.sviperll.repository;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author vir
 */
class SimpleSQLConnection implements SQLConnection {
    static SQLConnection createInstance(Connection connection) {
        return new SimpleSQLConnection(connection);
    }

    private final AutocommitState autoCommitState = new AutocommitState();
    private final TransactionState transactionState = new TransactionState();
    private final Connection connection;
    private SQLTransactionManager state;

    private SimpleSQLConnection(Connection connection) {
        this.connection = connection;
        this.state = autoCommitState;
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatementWithAutogeneratedKeys(String sql) throws SQLException {
        return connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    }

    @Override
    public PreparedStatement prepareStatementWithoutAutogeneratedKeys(String sql) throws SQLException {
        return connection.prepareStatement(sql, Statement.NO_GENERATED_KEYS);
    }

    @Override
    public void close() throws SQLException {
        state.rollbackTransactionIfNotCommited();
        connection.close();
    }

    @Override
    public void beginTransaction(SQLTransactionIsolationLevel level) throws SQLException {
        state.beginTransaction(level);
    }

    @Override
    public void beginTransaction() throws SQLException {
        state.beginTransaction();
    }

    @Override
    public void commitTransaction() throws SQLException {
        state.commitTransaction();
    }

    @Override
    public void rollbackTransaction() throws SQLException {
        state.rollbackTransaction();
    }

    @Override
    public void rollbackTransactionIfNotCommited() throws SQLException {
        state.rollbackTransactionIfNotCommited();
    }

    private class AutocommitState implements SQLTransactionManager {
        @Override
        public void beginTransaction() throws SQLException {
            connection.setAutoCommit(false);
            state = transactionState;
        }

        @Override
        public void beginTransaction(SQLTransactionIsolationLevel level) throws SQLException {
            connection.setAutoCommit(false);
            setTransactionIsolationLevel(level);
            state = transactionState;
        }

        private void setTransactionIsolationLevel(SQLTransactionIsolationLevel level) throws SQLException,
                                                                                             IllegalArgumentException {
            switch (level) {
                case NONE:
                    connection.setTransactionIsolation(Connection.TRANSACTION_NONE);
                    break;
                case READ_COMMITTED:
                    connection.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
                    break;
                case READ_UNCOMMITTED:
                    connection.setTransactionIsolation(Connection.TRANSACTION_READ_UNCOMMITTED);
                    break;
                case REPEATABLE_READ:
                    connection.setTransactionIsolation(Connection.TRANSACTION_REPEATABLE_READ);
                    break;
                case SERIALIZABLE:
                    connection.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
                    break;
                default:
                    throw new IllegalArgumentException("Unsupported transaction isolation level: " + level);
            }
        }

        @Override
        public void commitTransaction() throws SQLException {
            throw new UnsupportedOperationException("You should begin transaction first.");
        }

        @Override
        public void rollbackTransaction() throws SQLException {
            throw new UnsupportedOperationException("You should begin transaction first.");
        }

        @Override
        public void rollbackTransactionIfNotCommited() throws SQLException {
        }
    }

    private class TransactionState implements SQLTransactionManager {
        @Override
        public void beginTransaction() throws SQLException {
            throw new UnsupportedOperationException("Transaction already started.");
        }

        @Override
        public void beginTransaction(SQLTransactionIsolationLevel level) throws SQLException {
            throw new UnsupportedOperationException("Transaction already started.");
        }

        @Override
        public void commitTransaction() throws SQLException {
            connection.commit();
            state = autoCommitState;
            connection.setAutoCommit(true);
        }

        @Override
        public void rollbackTransaction() throws SQLException {
            connection.rollback();
            state = autoCommitState;
            connection.setAutoCommit(true);
        }

        @Override
        public void rollbackTransactionIfNotCommited() throws SQLException {
            rollbackTransaction();
        }
    }
}
